org: matiasmeneses
service: api-alumnos-propuesto

provider:
  name: aws
  runtime: python3.12
  iam:
    role: arn:aws:iam::344494306973:role/LabRole

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda
  crear:
    handler: CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true
          integration: lambda
  modificar:
    handler: ModificarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/modificar
          method: put
          cors: true
          integration: lambda
  eliminar:
    handler: EliminarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/eliminar
          method: delete
          cors: true
          integration: lambda
  buscar:
    handler: BuscarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/buscar
          method: post
          cors: true
          integration: lambda


